import Head from "next/head";
import Home1 from "../components/Home";

export default function Home() {
  return (
    <div className="w-full h-full bg-light">
      <Head>
        <title>Money Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home1 />
    </div>
  );
}
